---
- name: Install | detect old RabbitMQ repo
  shell:
    executable: /bin/bash
    cmd: |
      if \
        [[ -e /etc/apt/sources.list.d/rabbitmq.list ]] \
        && ! grep --quiet 'com.rabbitmq.team.gpg' /etc/apt/sources.list.d/rabbitmq.list
      then
        echo old
      fi
  register: resp
  changed_when: false

- name: Install | removed old RabbitMQ repo
  when: resp.stdout == 'old'
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/rabbitmq.list
    - /usr/share/keyrings/rabbitmq.9F4587F226208342.asc
    - /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.asc
    - /usr/share/keyrings/com.rabbitmq.team.asc


- name: Install | install CA certificates for get_url
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    update_cache: true
    state: present

# Commenting the tasks belows because in Ubuntu 24 if we use apt repos maintained by Team RabbitMQ then we are forced to use rabbitmq-server >= 4.1

# - name: Install | team RabbitMQ main signing key
#   ansible.builtin.shell:
#     executable: /bin/bash
#     creates: /usr/share/keyrings/com.rabbitmq.team.gpg
#     cmd: |
#       set -o pipefail
#       curl --fail --location --silent --tlsv1 \
#           https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA \
#         | gpg --dearmor \
#         > /usr/share/keyrings/com.rabbitmq.team.gpg

# - name: Install | add apt repositories maintained by Team RabbitMQ
#   ansible.builtin.copy:
#     dest: /etc/apt/sources.list.d/rabbitmq.list
#     mode: u+r
#     content: |
#       ## Modern Erlang/OTP releases
#       ##
#       deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb1.rabbitmq.com/rabbitmq-erlang/ubuntu/noble noble main
#       deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb2.rabbitmq.com/rabbitmq-erlang/ubuntu/noble noble main

#       ## Provides modern RabbitMQ releases
#       ##
#       deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb1.rabbitmq.com/rabbitmq-server/ubuntu/noble noble main
#       deb [arch=amd64 signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] https://deb2.rabbitmq.com/rabbitmq-server/ubuntu/noble noble main

# NOTE: for ubuntu 24 oldest version of rabbitmq available is 3.12.1
- name: Install | Erlang and RabbitMQ
  ansible.builtin.apt:
    name:
      - 'erlang-base=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-asn1=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-crypto=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-eldap=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-ftp=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-inets=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-mnesia=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-os-mon=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-parsetools=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-public-key=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-runtime-tools=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-snmp=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-ssl=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-syntax-tools=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-tftp=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-tools=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'erlang-xmerl=1:25.3.2.8+dfsg-1ubuntu4.6'
      - 'rabbitmq-server=3.12.1-1ubuntu1.2'
    update_cache: true
    state: fixed

- name: Install | pin Erlang version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/erlang
    content: |
      Package: erlang*
      Pin: version 1:25.3.2.8+dfsg-1ubuntu4.6
      Pin-Priority: 1001
    mode: u+r

- name: Install | pin RabbitMQ version
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/rabbitmq
    content: |
      Package: rabbitmq-server
      Pin: version 3.12.1-1ubuntu1.2
      Pin-Priority: 1001
    mode: u+r
