---
- name: Base | prepare
  ansible.builtin.import_playbook: prepare.yml


- name: Prepare | CentOS prepare for iRODS
  hosts: CentOS
  tasks:
    - name: CentOS | install epel repo
      ansible.builtin.package:
        name: epel-release
        state: present

    - name: CentOS | install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: CentOS | install yum_versionlock requirements
      ansible.builtin.package:
        name:
          - yum
          - yum-versionlock
        state: present

    - name: CentOS | install iRODS package repository signing key
      ansible.builtin.rpm_key:
        key: https://packages.irods.org/irods-signing-key.asc

    - name: CentOS | install iRODS repository
      ansible.builtin.get_url:
        url: https://packages.irods.org/renci-irods.yum.repo
        dest: /etc/yum.repos.d/renci-irods.yum.repo
        mode: u+r

    - name: CentOS | force import of GPG key
      ansible.builtin.shell: |
        if ! resp="$(yum --assumeyes updateinfo)"; then
          exit 1
        fi
        if [[ "$resp" =~ irods-signing-key ]]; then
          echo changed
        fi
      register: response
      changed_when: response.stdout == 'changed'

    - name: CentOS | lock irods packages to required version
      community.general.yum_versionlock:
        name:
          - irods-icommands-4.3.1
          - irods-database-plugin-postgres-4.3.1
          - irods-runtime-4.3.1
          - irods-server-4.3.1
        state: present


- name: Prepare | CentOS install DBMS
  hosts: irods_catalog:&CentOS
  tasks:
    - name: CentOS | install PostgreSQL server
      ansible.builtin.package:
        name:
          - postgresql-contrib
          - postgresql-odbc
          - postgresql-server
        state: present

    - name: CentOS | install prerequisites for psycopg2
      ansible.builtin.yum:
        name:
          - "@Development tools"
          - postgresql-devel
          - python3-devel
        state: present

    - name: CentOS | install prerequisites for pyodbc
      ansible.builtin.package:
        name:
          - gcc
          - gcc-c++
          - unixODBC-devel

    - name: CentOS | install pyodbc
      ansible.builtin.pip:
        name: pyodbc


- name: Prepare | CentOS initialize DBMS
  hosts: irods_catalog:&CentOS
  become: true
  become_user: postgres
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: CentOS | initialize PostgreSQL database cluster
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          if [[ -e "$PGDATA" ]] && [[ -z "$(ls --almost-all "$PGDATA")" ]]; then
            initdb --pgdata="$PGDATA" --auth=ident
          fi
      register: response
      changed_when: response.stdout != ''

    - name: CentOS | create PostgreSQL log directory
      ansible.builtin.file:
        path: /var/lib/pgsql/data/pg_log
        state: directory
        mode: u+r

    - name: CentOS | start PostgreSQL
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -o errexit
          if ! [[ -e "$PGDATA"/postmaster.pid ]]; then
            pg_ctl start > /dev/null
            echo changed
          fi
      register: response
      changed_when: response.stdout == 'changed'


- name: Prepare | Ubuntu prepare for iRODS
  hosts: Ubuntu
  tasks:
    - name: Ubuntu | ensure keyrings folder exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: a+rx
    - name: Ubuntu | install iRODS package repository signing key
      ansible.builtin.get_url:
        url: https://packages.irods.org/irods-signing-key.asc
        dest: /etc/apt/keyrings/irods-signing-key.asc
        mode: '0644'
        force: false

    - name: Ubuntu | install iRODS repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/renci-irods.list
        mode: u+rw
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/irods-signing-key.asc] https://packages.irods.org/apt/ {{ ansible_lsb.codename }} main

    - name: Ubuntu | lock iRODS packages to required version
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/irods
        mode: u+rw
        content: |
          Package: irods-*
          Pin: version 4.3.3-*
          Pin-Priority: 1001

    - name: Ubuntu | update apt cache
      ansible.builtin.apt:
        update_cache: true


- name: Prepare | Ubuntu install DBMS
  hosts: irods_catalog:&Ubuntu
  tasks:
    - name: Ubuntu | install PostgreSQL server
      ansible.builtin.package:
        name: postgresql
        state: present

    - name: Ubuntu | start PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Ubuntu | install prerequisites for psycopg2
      ansible.builtin.package:
        name: libpq-dev
        state: present


- name: Prepare | install iRODS
  hosts: all
  tasks:
    - name: Install irods-server
      ansible.builtin.package:
        name: irods-server


- name: Prepare | initialize irods DB plugin
  hosts: irods_catalog
  gather_facts: false
  tasks:
    - name: Install postgresql module prerequisites
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Install iRODS server
      ansible.builtin.package:
        name: irods-database-plugin-postgres
        state: present


- name: Prepare | initialize DBMS
  hosts: irods_catalog
  become: true
  become_user: postgres
  become_flags: '-i'
  gather_facts: false
  tasks:
    - name: Create ICAT DB
      community.postgresql.postgresql_db:
        name: ICAT

    - name: Create iRODS user
      community.postgresql.postgresql_user:
        name: irods
        password: testpassword

    - name: Grant iRODS user full access to ICAT DB
      community.postgresql.postgresql_privs:
        db: postgres
        privs: ALL
        type: database
        obj: ICAT
        roles: irods

    - name: Configure irods user ICAT access
      community.postgresql.postgresql_pg_hba:
        dest: "{{ pg_hba_path }}"
        contype: host
        users: irods
        source: 127.0.0.1/32
        databases: ICAT
        method: md5
        state: present
      notify: Reload postgres, {{ ansible_distribution }}

    - name: Remove ident access to DBMS
      community.postgresql.postgresql_pg_hba:
        dest: "{{ pg_hba_path }}"
        contype: host
        users: all
        source: "{{ item }}"
        databases: all
        method: md5
        state: present
      loop:
        - 127.0.0.1/32
        - ::1/128
      notify: Reload postgres, {{ ansible_distribution }}

  handlers:
    - name: Reload postgres, CentOS
      ansible.builtin.command: pg_ctl reload
      changed_when: true

    - name: Reload postgres, Ubuntu
      ansible.builtin.service:
        name: postgresql
        state: reloaded
