---
- name: Group hosts by OS
  hosts: all
  tasks:
    - name: Group
      ansible.builtin.group_by:
        key: "{{ ansible_distribution }}"
      changed_when: false


- name: Prepare | Ubuntu base
  hosts: Ubuntu
  tasks:
    - name: Ubuntu | update apt cache
      ansible.builtin.apt:
        update_cache: true


- name: Prepare | base
  hosts: all
  gather_facts: false
  tasks:
    - name: Install jsonschema
      ansible.builtin.package:
        name: python3-jsonschema
        state: present
