#!/usr/bin/env bash
#
# Usage:
#  build INC_FILE
#
# PARAMETERS:
#  INC_FILE  The absolute path to a file including the build time environment
#            variables. See README.md for details.
#
# Builds the five docker images with the provided configuration values.
#
# © 2025 The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

EXEC_NAME="$(readlink --canonicalize "$0")"
readonly EXEC_NAME


main()
{
  local baseDir
  baseDir="$(dirname "$EXEC_NAME")"

  local cfg="$*"

  if [ -z "$cfg" ]; then
    printf 'An environment variable include file is needed.\n' >&2
    return 1
  fi

  if ! [[ "$cfg" =~ ^/ ]]; then
    cfg="$(pwd)"/"$cfg"
  fi

  # shellcheck disable=SC1090
  . "$cfg"

  local os
  for os in alma10 centos7 ubuntu2204 ubuntu2404; do
    local buildArgs=(
#      --no-cache
      --file="$baseDir"/base/Dockerfile."$os"
      --tag=test-env-base:"$os"
    )

    docker buildx build "${buildArgs[@]}" "$baseDir"
  done

  local composeArgs=(
    --file="$baseDir"/docker-compose.yml
    --project-name="$ENV_NAME"
    build
#    --no-cache
  )

  if ! command -v docker-compose > /dev/null; then
    docker compose "${composeArgs[@]}"
  else
    docker-compose "${composeArgs[@]}"
  fi
}


main "$@"
